### ISSUE TITLE
Links wanted? (Search Engine Optimization)

### ISSUE THREAD

**Issue by boaks** [core-wg/wiki#1]
Hi Core-WG,

very great idea!

To be listed in web-searchs, links from other side's helps to get good positions in such results.
Therefore two questions:

Do you have considered to edit some related wikipedia pages to provide a link to this wiki?
[wikipedia de](https://de.wikipedia.org/wiki/Constrained_Application_Protocol)
[wikipedia en](https://en.wikipedia.org/wiki/Constrained_Application_Protocol)

Do you have considered to be linked by some implementation web-pages? 
(For Eclipse/Californium I can add a link, if wanted)

**Comment by chrysn** [comment]
> Do you have considered to edit some related wikipedia pages to provide a link to this wiki?

Linking from WP and other generic pages on the topic will at some point
make sense, but I'd hope to gather a bit more input before aiming there,
because I think after being turned down once on grounds of lack of
quality, it's harder to get in there on a second attempt rather than
getting it right the first time.

> (For Eclipse/Californium I can add a link, if wanted)

Pointing there from library documentation at the point where the
protocol is introduced and assertions on the user's familiarity with the
protocol are made would make sense -- again, provided the content here
is suitable (so far it's one-man-show ramblings).

I think that the most valuable of this will be when FAQ questions pop
up, and library maintainers can close them quickly with a refence to an
existing FAQ item.

**Comment by boaks** [comment]
:-).

OK, we will see, when it's the right time.
